[package]
name = "http-server"
version = "0.1.0"
authors = ["Livio Ribeiro <livioribeiro@outlook.com>"]

[dependencies]
time = "^0.1"
regex = "^0.1"
threadpool = "^0.1"
url = "^0.2"
conduit-mime-types = "^0.7"
argparse = "*"

[[bin]]
name = "server-bin"
doc = false
test = false
